import {CriteriaDefinition} from "@/shared/staticData/audit/types/types";

export function getCriteriaLengths(conformance: 'A' | 'AA' | 'AAA'){
  const map = {
    A: 31,
    AA: 55, // A + 24 for AA
    AAA: 86 // AA + 31 for AAA
  }
  return map[conformance];
}

export function getStaticCriteriaById(id: string): CriteriaDefinition {
    return WCAGCriterias.filter(c => c.id === id)[0];
}

export const WCAGCriterias: CriteriaDefinition[] = [
  {
    id: '1-1-1-perceivable',
    category: "Perceivable",
    guideLine: 'criteria.list.1-1-1-non-text-content.guideline',
    name: 'criteria.list.1-1-1-non-text-content.name',
    conformance: 'A',
    referenceLink: 'https://www.w3.org/WAI/WCAG22/quickref/#non-text-content',
  },
  {
    id: '1-2-1-perceivable',
    category: "Perceivable",
    guideLine: 'criteria.list.1-2-1-audio-only-and-video-only-prerecorded.guideline',
    name: 'criteria.list.1-2-1-audio-only-and-video-only-prerecorded.name',
    conformance: 'A',
    referenceLink: 'https://www.w3.org/WAI/WCAG22/quickref/#audio-only-and-video-only-prerecorded',
  },
  {
    id: '1-2-2-perceivable',
    category: "Perceivable",
    guideLine: 'criteria.list.1-2-2-captions-prerecorded.guideline',
    name: 'criteria.list.1-2-2-captions-prerecorded.name',
    conformance: 'A',
    referenceLink: 'https://www.w3.org/WAI/WCAG22/quickref/#captions-prerecorded',
  },
  {
    id: '1-2-3-perceivable',
    category: "Perceivable",
    guideLine: 'criteria.list.1-2-3-audio-description-or-media-alternative-prerecorded.guideline',
    name: 'criteria.list.1-2-3-audio-description-or-media-alternative-prerecorded.name',
    conformance: 'A',
    referenceLink: 'https://www.w3.org/WAI/WCAG22/quickref/#audio-description-or-media-alternative-prerecorded',
  },
  {
    id: '1-2-4-perceivable',
    category: "Perceivable",
    guideLine: 'criteria.list.1-2-4-captions-live.guideline',
    name: 'criteria.list.1-2-4-captions-live.name',
    conformance: 'AA',
    referenceLink: 'https://www.w3.org/WAI/WCAG22/quickref/#captions-live',
  },
  {
    id: '1-2-5-perceivable',
    category: "Perceivable",
    guideLine: 'criteria.list.1-2-5-audio-description-prerecorded.guideline',
    name: 'criteria.list.1-2-5-audio-description-prerecorded.name',
    conformance: 'AA',
    referenceLink: 'https://www.w3.org/WAI/WCAG22/quickref/#audio-description-prerecorded',
  },
  {
    id: '1-2-6-perceivable',
    category: "Perceivable",
    guideLine: 'criteria.list.1-2-6-sign-language-prerecorded.guideline',
    name: 'criteria.list.1-2-6-sign-language-prerecorded.name',
    conformance: 'AAA',
    referenceLink: 'https://www.w3.org/WAI/WCAG22/quickref/#sign-language-prerecorded',
  },
  {
    id: '1-2-7-perceivable',
    category: "Perceivable",
    guideLine: 'criteria.list.1-2-7-extended-audio-description-prerecorded.guideline',
    name: 'criteria.list.1-2-7-extended-audio-description-prerecorded.name',
    conformance: 'AAA',
    referenceLink: 'https://www.w3.org/WAI/WCAG22/quickref/#extended-audio-description-prerecorded',
  },
  {
    id: '1-2-8-perceivable',
    category: "Perceivable",
    guideLine: 'criteria.list.1-2-8-media-alternative-prerecorded.guideline',
    name: 'criteria.list.1-2-8-media-alternative-prerecorded.name',
    conformance: 'AAA',
    referenceLink: 'https://www.w3.org/WAI/WCAG22/quickref/#media-alternative-prerecorded',
  },
  {
    id: '1-2-9-perceivable',
    category: "Perceivable",
    guideLine: 'criteria.list.1-2-9-audio-only-live.guideline',
    name: 'criteria.list.1-2-9-audio-only-live.name',
    conformance: 'AAA',
    referenceLink: 'https://www.w3.org/WAI/WCAG22/quickref/#audio-only-live',
  },
  {
    id: '1-3-1-perceivable',
    category: "Perceivable",
    guideLine: 'criteria.list.1-3-1-info-and-relationships.guideline',
    name: 'criteria.list.1-3-1-info-and-relationships.name',
    conformance: 'A',
    referenceLink: 'https://www.w3.org/WAI/WCAG22/quickref/#info-and-relationships',
  },
  {
    id: '1-3-2-perceivable',
    category: "Perceivable",
    guideLine: 'criteria.list.1-3-2-meaningful-sequence.guideline',
    name: 'criteria.list.1-3-2-meaningful-sequence.name',
    conformance: 'A',
    referenceLink: 'https://www.w3.org/WAI/WCAG22/quickref/#meaningful-sequence',
  },
  {
    id: '1-3-3-perceivable',
    category: "Perceivable",
    guideLine: 'criteria.list.1-3-3-sensory-characteristics.guideline',
    name: 'criteria.list.1-3-3-sensory-characteristics.name',
    conformance: 'A',
    referenceLink: 'https://www.w3.org/WAI/WCAG22/quickref/#sensory-characteristics',
  },
  {
    id: '1-3-4-perceivable',
    category: "Perceivable",
    guideLine: 'criteria.list.1-3-4-orientation.guideline',
    name: 'criteria.list.1-3-4-orientation.name',
    conformance: 'AA',
    referenceLink: 'https://www.w3.org/WAI/WCAG22/quickref/#orientation',
  },
  {
    id: '1.3-5-perceivable',
    category: "Perceivable",
    guideLine: 'criteria.list.1-3-5-identify-input-purpose.guideline',
    name: 'criteria.list.1-3-5-identify-input-purpose.name',
    conformance: 'AA',
    referenceLink: 'https://www.w3.org/WAI/WCAG22/quickref/#identify-input-purpose',
  },
  {
    id: '1-3-6-perceivable',
    category: "Perceivable",
    guideLine: 'criteria.list.1-3-6-identify-purpose.guideline',
    name: 'criteria.list.1-3-6-identify-purpose.name',
    conformance: 'AAA',
    referenceLink: 'https://www.w3.org/WAI/WCAG22/quickref/#identify-purpose',
  },
  {
    id: '1-4-1-perceivable',
    category: "Perceivable",
    guideLine: 'criteria.list.1-4-1-use-of-color.guideline',
    name: 'criteria.list.1-4-1-use-of-color.name',
    conformance: 'A',
    referenceLink: 'https://www.w3.org/WAI/WCAG22/quickref/#use-of-color',
  },
  {
    id: '1-4-2-perceivable',
    category: "Perceivable",
    guideLine: 'criteria.list.1-4-2-audio-control.guideline',
    name: 'criteria.list.1-4-2-audio-control.name',
    conformance: 'A',
    referenceLink: 'https://www.w3.org/WAI/WCAG22/quickref/#audio-control',
  },
  {
    id: '1-4-3-perceivable',
    category: "Perceivable",
    guideLine: 'criteria.list.1-4-3-contrast-minimum.guideline',
    name: 'criteria.list.1-4-3-contrast-minimum.name',
    conformance: 'AA',
    referenceLink: 'https://www.w3.org/WAI/WCAG22/quickref/#contrast-minimum',
  },
  {
    id: '1-4-4-perceivable',
    category: "Perceivable",
    guideLine: 'criteria.list.1-4-4-resize-text.guideline',
    name: 'criteria.list.1-4-4-resize-text.name',
    conformance: 'AA',
    referenceLink: 'https://www.w3.org/WAI/WCAG22/quickref/#resize-text',
  },
  {
    id: '1-4-5-perceivable',
    category: "Perceivable",
    guideLine: 'criteria.list.1-4-5-images-of-text.guideline',
    name: 'criteria.list.1-4-5-images-of-text.name',
    conformance: 'AA',
    referenceLink: 'https://www.w3.org/WAI/WCAG22/quickref/#images-of-text',
  },
  {
    id: '1-4-6-perceivable',
    category: "Perceivable",
    guideLine: 'criteria.list.1-4-6-contrast-enhanced.guideline',
    name: 'criteria.list.1-4-6-contrast-enhanced.name',
    conformance: 'AAA',
    referenceLink: 'https://www.w3.org/WAI/WCAG22/quickref/#contrast-enhanced',
  },
  {
    id: '1-4-7-perceivable',
    category: "Perceivable",
    guideLine: 'criteria.list.1-4-7-low-or-no-background-audio.guideline',
    name: 'criteria.list.1-4-7-low-or-no-background-audio.name',
    conformance: 'AAA',
    referenceLink: 'https://www.w3.org/WAI/WCAG22/quickref/#low-or-no-background-audio',
  },
  {
    id: '1-4-8-perceivable',
    category: "Perceivable",
    guideLine: 'criteria.list.1-4-8-visual-presentation.guideline',
    name: 'criteria.list.1-4-8-visual-presentation.name',
    conformance: 'AAA',
    referenceLink: 'https://www.w3.org/WAI/WCAG22/quickref/#visual-presentation',
  },
  {
    id: '1-4-9-perceivable',
    category: "Perceivable",
    guideLine: 'criteria.list.1-4-9-images-of-text-no-exception.guideline',
    name: 'criteria.list.1-4-9-images-of-text-no-exception.name',
    conformance: 'AAA',
    referenceLink: 'https://www.w3.org/WAI/WCAG22/quickref/#images-of-text-no-exception',
  },
  {
    id: '1-4-10-perceivable',
    category: "Perceivable",
    guideLine: 'criteria.list.1-4-10-reflow.guideline',
    name: 'criteria.list.1-4-10-reflow.name',
    conformance: 'AA',
    referenceLink: 'https://www.w3.org/WAI/WCAG22/quickref/#reflow',
  },
  {
    id: '1-4-11-perceivable',
    category: "Perceivable",
    guideLine: 'criteria.list.1-4-11-non-text-contrast.guideline',
    name: 'criteria.list.1-4-11-non-text-contrast.name',
    conformance: 'AA',
    referenceLink: 'https://www.w3.org/WAI/WCAG22/quickref/#non-text-contrast',
  },
  {
    id: '1-4-12-perceivable',
    category: "Perceivable",
    guideLine: 'criteria.list.1-4-12-text-spacing.guideline',
    name: 'criteria.list.1-4-12-text-spacing.name',
    conformance: 'AA',
    referenceLink: 'https://www.w3.org/WAI/WCAG22/quickref/#text-spacing',
  },
  {
    id: '1-4-13-perceivable',
    category: "Perceivable",
    guideLine: 'criteria.list.1-4-13-content-on-hover-or-focus.guideline',
    name: 'criteria.list.1-4-13-content-on-hover-or-focus.name',
    conformance: 'AA',
    referenceLink: 'https://www.w3.org/WAI/WCAG22/quickref/#content-on-hover-or-focus',
  },
  {
    id: '2-1-1-operable',
    category: "Operable",
    guideLine: 'criteria.list.2-1-1-keyboard.guideline',
    name: 'criteria.list.2-1-1-keyboard.name',
    conformance: 'A',
    referenceLink: 'https://www.w3.org/WAI/WCAG22/quickref/#keyboard',
  },
  {
    id: '2-1-2-operable',
    category: "Operable",
    guideLine: 'criteria.list.2-1-2-no-keyboard-trap.guideline',
    name: 'criteria.list.2-1-2-no-keyboard-trap.name',
    conformance: 'A',
    referenceLink: 'https://www.w3.org/WAI/WCAG22/quickref/#no-keyboard-trap',
  },
  {
    id: '2-1-3-operable',
    category: "Operable",
    guideLine: 'criteria.list.2-1-3-keyboard-no-exception.guideline',
    name: 'criteria.list.2-1-3-keyboard-no-exception.name',
    conformance: 'AAA',
    referenceLink: 'https://www.w3.org/WAI/WCAG22/quickref/#keyboard-no-exception',
  },
  {
    id: '2-1-4-operable',
    category: "Operable",
    guideLine: 'criteria.list.2-1-4-character-key-shortcuts.guideline',
    name: 'criteria.list.2-1-4-character-key-shortcuts.name',
    conformance: 'A',
    referenceLink: 'https://www.w3.org/WAI/WCAG22/quickref/#character-key-shortcuts',
  },
  {
    id: '2-2-1-operable',
    category: "Operable",
    guideLine: 'criteria.list.2-2-1-timing-adjustable.guideline',
    name: 'criteria.list.2-2-1-timing-adjustable.name',
    conformance: 'A',
    referenceLink: 'https://www.w3.org/WAI/WCAG22/quickref/#timing-adjustable',
  },
  {
    id: '2-2-2-operable',
    category: "Operable",
    guideLine: 'criteria.list.2-2-2-pause-stop-hide.guideline',
    name: 'criteria.list.2-2-2-pause-stop-hide.name',
    conformance: 'A',
    referenceLink: 'https://www.w3.org/WAI/WCAG22/quickref/#pause-stop-hide',
  },
  {
    id: '2-2-3-operable',
    category: "Operable",
    guideLine: 'criteria.list.2-2-3-no-timing.guideline',
    name: 'criteria.list.2-2-3-no-timing.name',
    conformance: 'AAA',
    referenceLink: 'https://www.w3.org/WAI/WCAG22/quickref/#no-timing',
  },
  {
    id: '2-2-4-operable',
    category: "Operable",
    guideLine: 'criteria.list.2-2-4-interruptions.guideline',
    name: 'criteria.list.2-2-4-interruptions.name',
    conformance: 'AAA',
    referenceLink: 'https://www.w3.org/WAI/WCAG22/quickref/#interruptions',
  },
  {
    id: '2-2-5-operable',
    category: "Operable",
    guideLine: 'criteria.list.2-2-5-re-authenticating.guideline',
    name: 'criteria.list.2-2-5-re-authenticating.name',
    conformance: 'AAA',
    referenceLink: 'https://www.w3.org/WAI/WCAG22/quickref/#re-authenticating',
  },
  {
    id: '2-2-6-operable',
    category: "Operable",
    guideLine: 'criteria.list.2-2-6-timeouts.guideline',
    name: 'criteria.list.2-2-6-timeouts.name',
    conformance: 'AAA',
    referenceLink: 'https://www.w3.org/WAI/WCAG22/quickref/#timeouts',
  },
  {
    id: '2-3-1-operable',
    category: "Operable",
    guideLine: 'criteria.list.2-3-1-three-flashes-or-below-threshold.guideline',
    name: 'criteria.list.2-3-1-three-flashes-or-below-threshold.name',
    conformance: 'A',
    referenceLink: 'https://www.w3.org/WAI/WCAG22/quickref/#three-flashes-or-below-threshold',
  },
  {
    id: '2-3-2-operable',
    category: "Operable",
    guideLine: 'criteria.list.2-3-2-three-flashes.guideline',
    name: 'criteria.list.2-3-2-three-flashes.name',
    conformance: 'AAA',
    referenceLink: 'https://www.w3.org/WAI/WCAG22/quickref/#three-flashes',
  },
  {
    id: '2-3-3-operable',
    category: "Operable",
    guideLine: 'criteria.list.2-3-3-animation-from-interactions.guideline',
    name: 'criteria.list.2-3-3-animation-from-interactions.name',
    conformance: 'AAA',
    referenceLink: 'https://www.w3.org/WAI/WCAG22/quickref/#animation-from-interactions',
  },
  {
    id: '2-4-1-operable',
    category: "Operable",
    guideLine: 'criteria.list.2-4-1-bypass-blocks.guideline',
    name: 'criteria.list.2-4-1-bypass-blocks.name',
    conformance: 'A',
    referenceLink: 'https://www.w3.org/WAI/WCAG22/quickref/#bypass-blocks',
  },
  {
    id: '2-4-2-operable',
    category: "Operable",
    guideLine: 'criteria.list.2-4-2-page-titled.guideline',
    name: 'criteria.list.2-4-2-page-titled.name',
    conformance: 'A',
    referenceLink: 'https://www.w3.org/WAI/WCAG22/quickref/#page-titled',
  },
  {
    id: '2-4-3-operable',
    category: "Operable",
    guideLine: 'criteria.list.2-4-3-focus-order.guideline',
    name: 'criteria.list.2-4-3-focus-order.name',
    conformance: 'A',
    referenceLink: 'https://www.w3.org/WAI/WCAG22/quickref/#focus-order',
  },
  {
    id: '2-4-4-operable',
    category: "Operable",
    guideLine: 'criteria.list.2-4-4-link-purpose-in-context.guideline',
    name: 'criteria.list.2-4-4-link-purpose-in-context.name',
    conformance: 'A',
    referenceLink: 'https://www.w3.org/WAI/WCAG22/quickref/#link-purpose-in-context',
  },
  {
    id: '2-4-5-operable',
    category: "Operable",
    guideLine: 'criteria.list.2-4-5-multiple-ways.guideline',
    name: 'criteria.list.2-4-5-multiple-ways.name',
    conformance: 'AA',
    referenceLink: 'https://www.w3.org/WAI/WCAG22/quickref/#multiple-ways',
  },
  {
    id: '2-4-6-operable',
    category: "Operable",
    guideLine: 'criteria.list.2-4-6-headings-and-labels.guideline',
    name: 'criteria.list.2-4-6-headings-and-labels.name',
    conformance: 'AA',
    referenceLink: 'https://www.w3.org/WAI/WCAG22/quickref/#headings-and-labels',
  },
  {
    id: '2-4-7-operable',
    category: "Operable",
    guideLine: 'criteria.list.2-4-7-focus-visible.guideline',
    name: 'criteria.list.2-4-7-focus-visible.name',
    conformance: 'AA',
    referenceLink: 'https://www.w3.org/WAI/WCAG22/quickref/#focus-visible',
  },
  {
    id: '2-4-8-operable',
    category: "Operable",
    guideLine: 'criteria.list.2-4-8-location.guideline',
    name: 'criteria.list.2-4-8-location.name',
    conformance: 'AAA',
    referenceLink: 'https://www.w3.org/WAI/WCAG22/quickref/#location',
  },
  {
    id: '2-4-9-operable',
    category: "Operable",
    guideLine: 'criteria.list.2-4-9-link-purpose-link-only.guideline',
    name: 'criteria.list.2-4-9-link-purpose-link-only.name',
    conformance: 'AAA',
    referenceLink: 'https://www.w3.org/WAI/WCAG22/quickref/#link-purpose-link-only',
  },
  {
    id: '2-4-10-operable',
    category: "Operable",
    guideLine: 'criteria.list.2-4-10-section-headings.guideline',
    name: 'criteria.list.2-4-10-section-headings.name',
    conformance: 'AAA',
    referenceLink: 'https://www.w3.org/WAI/WCAG22/quickref/#section-headings',
  },
  {
    id: '2-4-11-operable',
    category: "Operable",
    guideLine: 'criteria.list.2-4-11-focus-not-obscured-minimum.guideline',
    name: 'criteria.list.2-4-11-focus-not-obscured-minimum.name',
    conformance: 'AA',
    referenceLink: 'https://www.w3.org/WAI/WCAG22/quickref/#focus-not-obscured-minimum',
  },
  {
    id: '2-4-12-operable',
    category: "Operable",
    guideLine: 'criteria.list.2-4-12-focus-not-obscured-enhanced.guideline',
    name: 'criteria.list.2-4-12-focus-not-obscured-enhanced.name',
    conformance: 'AAA',
    referenceLink: 'https://www.w3.org/WAI/WCAG22/quickref/#focus-not-obscured-enhanced',
  },
  {
    id: '2-4-13-operable',
    category: "Operable",
    guideLine: 'criteria.list.2-4-13-focus-appearance.guideline',
    name: 'criteria.list.2-4-13-focus-appearance.name',
    conformance: 'AAA',
    referenceLink: 'https://www.w3.org/WAI/WCAG22/quickref/#focus-appearance',
  },
  {
    id: '2-5-1-operable',
    category: "Operable",
    guideLine: 'criteria.list.2-5-1-pointer-gestures.guideline',
    name: 'criteria.list.2-5-1-pointer-gestures.name',
    conformance: 'A',
    referenceLink: 'https://www.w3.org/WAI/WCAG22/quickref/#pointer-gestures',
  },
  {
    id: '2-5-2-operable',
    category: "Operable",
    guideLine: 'criteria.list.2-5-2-pointer-cancellation.guideline',
    name: 'criteria.list.2-5-2-pointer-cancellation.name',
    conformance: 'A',
    referenceLink: 'https://www.w3.org/WAI/WCAG22/quickref/#pointer-cancellation',
  },
  {
    id: '2-5-3-operable',
    category: "Operable",
    guideLine: 'criteria.list.2-5-3-label-in-name.guideline',
    name: 'criteria.list.2-5-3-label-in-name.name',
    conformance: 'A',
    referenceLink: 'https://www.w3.org/WAI/WCAG22/quickref/#label-in-name',
  },
  {
    id: '2-5-4-operable',
    category: "Operable",
    guideLine: 'criteria.list.2-5-4-motion-actuation.guideline',
    name: 'criteria.list.2-5-4-motion-actuation.name',
    conformance: 'A',
    referenceLink: 'https://www.w3.org/WAI/WCAG22/quickref/#motion-actuation',
  },
  {
    id: '2-5-5-operable',
    category: "Operable",
    guideLine: 'criteria.list.2-5-5-target-size-enhanced.guideline',
    name: 'criteria.list.2-5-5-target-size-enhanced.name',
    conformance: 'AAA',
    referenceLink: 'https://www.w3.org/WAI/WCAG22/quickref/#target-size-enhanced',
  },
  {
    id: '2-5-6-operable',
    category: "Operable",
    guideLine: 'criteria.list.2-5-6-concurrent-input-mechanisms.guideline',
    name: 'criteria.list.2-5-6-concurrent-input-mechanisms.name',
    conformance: 'AAA',
    referenceLink: 'https://www.w3.org/WAI/WCAG22/quickref/#concurrent-input-mechanisms',
  },
  {
    id: '2-5-7-operable',
    category: "Operable",
    guideLine: 'criteria.list.2-5-7-dragging-movements.guideline',
    name: 'criteria.list.2-5-7-dragging-movements.name',
    conformance: 'AA',
    referenceLink: 'https://www.w3.org/WAI/WCAG22/quickref/#dragging-movements',
  },
  {
    id: '2-5-8-operable',
    category: "Operable",
    guideLine: 'criteria.list.2-5-8-target-size-minimum.guideline',
    name: 'criteria.list.2-5-8-target-size-minimum.name',
    conformance: 'AA',
    referenceLink: 'https://www.w3.org/WAI/WCAG22/quickref/#target-size-minimum',
  },
  {
    id: '3-1-1-understandable',
    category: "Understandable",
    guideLine: 'criteria.list.3-1-1-language-of-page.guideline',
    name: 'criteria.list.3-1-1-language-of-page.name',
    conformance: 'A',
    referenceLink: 'https://www.w3.org/WAI/WCAG22/quickref/#language-of-page',
  },
  {
    id: '3-1-2-understandable',
    category: "Understandable",
    guideLine: 'criteria.list.3-1-2-language-of-parts.guideline',
    name: 'criteria.list.3-1-2-language-of-parts.name',
    conformance: 'AA',
    referenceLink: 'https://www.w3.org/WAI/WCAG22/quickref/#language-of-parts',
  },
  {
    id: '3-1-3-understandable',
    category: "Understandable",
    guideLine: 'criteria.list.3-1-3-unusual-words.guideline',
    name: 'criteria.list.3-1-3-unusual-words.name',
    conformance: 'AAA',
    referenceLink: 'https://www.w3.org/WAI/WCAG22/quickref/#unusual-words',
  },
  {
    id: '3-1-4-understandable',
    category: "Understandable",
    guideLine: 'criteria.list.3-1-4-abbreviations.guideline',
    name: 'criteria.list.3-1-4-abbreviations.name',
    conformance: 'AAA',
    referenceLink: 'https://www.w3.org/WAI/WCAG22/quickref/#abbreviations',
  },
  {
    id: '3-1-5-understandable',
    category: "Understandable",
    guideLine: 'criteria.list.3-1-5-reading-conformance.guideline',
    name: 'criteria.list.3-1-5-reading-conformance.name',
    conformance: 'AAA',
    referenceLink: 'https://www.w3.org/WAI/WCAG22/quickref/#reading-conformance',
  },
  {
    id: '3-1-6-understandable',
    category: "Understandable",
    guideLine: 'criteria.list.3-1-6-pronunciation.guideline',
    name: 'criteria.list.3-1-6-pronunciation.name',
    conformance: 'AAA',
    referenceLink: 'https://www.w3.org/WAI/WCAG22/quickref/#pronunciation',
  },
  {
    id: '3-2-1-understandable',
    category: "Understandable",
    guideLine: 'criteria.list.3-2-1-on-focus.guideline',
    name: 'criteria.list.3-2-1-on-focus.name',
    conformance: 'A',
    referenceLink: 'https://www.w3.org/WAI/WCAG22/quickref/#on-focus',
  },
  {
    id: '3-2-2-understandable',
    category: "Understandable",
    guideLine: 'criteria.list.3-2-2-on-input.guideline',
    name: 'criteria.list.3-2-2-on-input.name',
    conformance: 'A',
    referenceLink: 'https://www.w3.org/WAI/WCAG22/quickref/#on-input',
  },
  {
    id: '3-2-3-understandable',
    category: "Understandable",
    guideLine: 'criteria.list.3-2-3-consistent-navigation.guideline',
    name: 'criteria.list.3-2-3-consistent-navigation.name',
    conformance: 'AA',
    referenceLink: 'https://www.w3.org/WAI/WCAG22/quickref/#consistent-navigation',
  },
  {
    id: '3-2-4-understandable',
    category: "Understandable",
    guideLine: 'criteria.list.3-2-4-consistent-identification.guideline',
    name: 'criteria.list.3-2-4-consistent-identification.name',
    conformance: 'AA',
    referenceLink: 'https://www.w3.org/WAI/WCAG22/quickref/#consistent-identification',
  },
  {
    id: '3-2-5-understandable',
    category: "Understandable",
    guideLine: 'criteria.list.3-2-5-change-on-request.guideline',
    name: 'criteria.list.3-2-5-change-on-request.name',
    conformance: 'AAA',
    referenceLink: 'https://www.w3.org/WAI/WCAG22/quickref/#change-on-request',
  },
  {
    id: '3-2-6-understandable',
    category: "Understandable",
    guideLine: 'criteria.list.3-2-6-consistent-help.guideline',
    name: 'criteria.list.3-2-6-consistent-help.name',
    conformance: 'A',
    referenceLink: 'https://www.w3.org/WAI/WCAG22/quickref/#consistent-help',
  },
  {
    id: '3-3-1-understandable',
    category: "Understandable",
    guideLine: 'criteria.list.3-3-1-error-identification.guideline',
    name: 'criteria.list.3-3-1-error-identification.name',
    conformance: 'A',
    referenceLink: 'https://www.w3.org/WAI/WCAG22/quickref/#error-identification',
  },
  {
    id: '3-3-2-understandable',
    category: "Understandable",
    guideLine: 'criteria.list.3-3-2-labels-or-instructions.guideline',
    name: 'criteria.list.3-3-2-labels-or-instructions.name',
    conformance: 'A',
    referenceLink: 'https://www.w3.org/WAI/WCAG22/quickref/#labels-or-instructions',
  },
  {
    id: '3-3-3-understandable',
    category: "Understandable",
    guideLine: 'criteria.list.3-3-3-error-suggestion.guideline',
    name: 'criteria.list.3-3-3-error-suggestion.name',
    conformance: 'AA',
    referenceLink: 'https://www.w3.org/WAI/WCAG22/quickref/#error-suggestion',
  },
  {
    id: '3-3-4-understandable',
    category: "Understandable",
    guideLine: 'criteria.list.3-3-4-error-prevention-legal-financial-data.guideline',
    name: 'criteria.list.3-3-4-error-prevention-legal-financial-data.name',
    conformance: 'AA',
    referenceLink: 'https://www.w3.org/WAI/WCAG22/quickref/#error-prevention-legal-financial-data',
  },
  {
    id: '3-3-5-understandable',
    category: "Understandable",
    guideLine: 'criteria.list.3-3-5-help.guideline',
    name: 'criteria.list.3-3-5-help.name',
    conformance: 'AAA',
    referenceLink: 'https://www.w3.org/WAI/WCAG22/quickref/#help',
  },
  {
    id: '3-3-6-understandable',
    category: "Understandable",
    guideLine: 'criteria.list.3-3-6-error-prevention-all.guideline',
    name: 'criteria.list.3-3-6-error-prevention-all.name',
    conformance: 'AAA',
    referenceLink: 'https://www.w3.org/WAI/WCAG22/quickref/#error-prevention-all',
  },
  {
    id: '3-3-7-understandable',
    category: "Understandable",
    guideLine: 'criteria.list.3-3-7-redundant-entry.guideline',
    name: 'criteria.list.3-3-7-redundant-entry.name',
    conformance: 'A',
    referenceLink: 'https://www.w3.org/WAI/WCAG22/quickref/#redundant-entry',
  },
  {
    id: '3-3-8-understandable',
    category: "Understandable",
    guideLine: 'criteria.list.3-3-8-accessible-authentication-minimum.guideline',
    name: 'criteria.list.3-3-8-accessible-authentication-minimum.name',
    conformance: 'AA',
    referenceLink: 'https://www.w3.org/WAI/WCAG22/quickref/#accessible-authentication-minimum',
  },
  {
    id: '3-3-9-understandable',
    category: "Understandable",
    guideLine: 'criteria.list.3-3-9-accessible-authentication-enhanced.guideline',
    name: 'criteria.list.3-3-9-accessible-authentication-enhanced.name',
    conformance: 'AAA',
    referenceLink: 'https://www.w3.org/WAI/WCAG22/quickref/#accessible-authentication-enhanced',
  },
  {
    id: '4-1-2-robust',
    category: "Robust",
    guideLine: 'criteria.list.4-1-2-name-role-value.guideline',
    name: 'criteria.list.4-1-2-name-role-value.name',
    conformance: 'A',
    referenceLink: 'https://www.w3.org/WAI/WCAG22/quickref/#name-role-value',
  },
  {
    id: '4-1-3-robust',
    category: "Robust",
    guideLine: 'criteria.list.4-1-3-status-messages.guideline',
    name: 'criteria.list.4-1-3-status-messages.name',
    conformance: 'AA',
    referenceLink: 'https://www.w3.org/WAI/WCAG22/quickref/#status-messages',
  }
]
